### ISSUE TITLE
Incorrect behavior in `users` tables with dates

### ISSUE THREAD

**Issue by corymartin** [xataio/client-ts#819] opened 2022-12-14 19:11 UTC
These issues are specific to tables named `users`, case-insensitive.
I have not observed the issues in tables by other names, and I have tried this in multiple databases.

Also, this follows a conversation with @kostasb from Discord
https://discord.com/channels/996791218879086662/1002130113565053008/1051530218394890271

#### Observed issues:
1. Dates do not appear in UI
    <img width="1163" alt="Screenshot 2022-12-14 at 12 34 30 PM" src="https://user-images.githubusercontent.com/687518/207674920-dbc13310-e3b2-413f-9d6a-cc2bbc3b432b.png">
    
    However the data is there when queried via client
    <img width="1203" alt="Screenshot 2022-12-14 at 1 22 12 PM" src="https://user-images.githubusercontent.com/687518/207676747-0f52aa20-7c0c-4d77-a752-9abf2f1de7e9.png">
2. Filtering by date does not work. The below query should return `null`, as it does in tables **NOT** named `users`.
    <img width="1203" alt="Screenshot 2022-12-14 at 1 28 30 PM" src="https://user-images.githubusercontent.com/687518/207679095-e3dc4566-bd9c-4d04-a57f-2315dd211e43.png">
3. Data from `users` is not available in "Search"
    <img width="760" alt="Screenshot 2022-12-14 at 2 07 20 PM" src="https://user-images.githubusercontent.com/687518/207691010-b578d4be-1c3d-452b-9b1a-ae54a7ef127e.png">

**To Reproduce**

1. Create a table `users` or `Users` in the Xata UI
2. Create schema via API
```zsh
curl -v -X PUT https://<workspace>.<region>.xata.sh/db/<database>:main/tables/users/schema  --header 'Content-Type: application/json' --header "Authorization: Bearer <api_key>" -d '
{
      "columns": [
        {
          "name": "handle",
          "type": "string",
          "unique": true
        },
        {
          "name": "_handle",
          "type": "string",
          "unique": true
        },
        {
          "name": "profile",
          "type": "object",
          "columns": [
            {
              "name": "name",
              "type": "string"
            },
            {
              "name": "bio",
              "type": "text"
            },
            {
              "name": "location",
              "type": "string"
            },
            {
              "name": "website",
              "type": "string"
            }
          ]
        },
        {
          "name": "settings",
          "type": "object",
          "columns": [
            {
              "name": "app_theme",
              "type": "string",
              "notNull": true,
              "defaultValue": "system"
            }
          ]
        },
        {
          "name": "created_at",
          "type": "datetime",
          "notNull": true,
          "defaultValue": "now"
        },
        {
          "name": "updated_at",
          "type": "datetime",
          "notNull": true,
          "defaultValue": "now"
        }
      ]
}'
```
3. Add a user via client. I used the generated client (`npx xata codegen`).
```ts
await xata.db.users.create('V7XH49jk5oWknYtn73wFwzsH74s1', {
  handle: 'test',
});
```

**Expected behavior**

For `users` data to work like data from other tables.

**Software version**

From package.json
```json
"dependencies" {
  "@xata.io/client": "^0.21.3"
},
"devDependencies" {
  "@xata.io/cli": "^0.11.4"
}
```

**Additional context**

I just started playing with Xata a few days ago, FYI.  I'm already a fan and hope to see you guys go far!

**Comment by tsg** [comment] 2022-12-14 20:36
hi @corymartin thanks a lot of for the excellent report! I can confirm there is a bug, it seems related to the `now` function generating the date with a slightly different format (nanoseconds vs milliseconds).

In my tests, equality date comparison don't work because of this, but `$gt` and `$lt` work as expected, for example:

```
const res = await xata.db.test
  .filter({
    $all: [
      {
        created_at: {
          $ge: "2022-12-14T19:56:00.895Z",
        },
      },
      {
        created_at: {
          $lt: "2022-12-14T19:56:00.896Z",
        },
      },
    ],
  })
  .getMany();
```

We'll work on fixing this ASAP. If you can avoid dates with default value `now` for the moment, that would avoid these issues.

**Comment by corymartin** [comment] 2022-12-14 21:10
Thanks @tsg 

However ‘now‘ did work as expected for me when the table was not named "users"

**Comment by tsg** [comment] 2022-12-17 18:53
@corymartin I forgot to write back, but the fix for these issues should be in since yesterday. Can you try again, please, and let me know if you notice any issues?

**Comment by corymartin** [comment] 2022-12-18 17:57
Thanks @tsg

It worked with the TS client `await xata.db.Table.create()`

However with transactions - which I realize is still in beta - I get an error:
```
FetcherError: Bulk operation failed

{
  status: 400,
  errors: [
    {
      index: 0,
      message: 'table [UserPrograms]: select record: invalid record: column [createdAt]: cannot be null'
    }
  ],
  requestId: '6f657ab5-e132-9ac3-b5c5-acbce46232fd',
  cause: undefined
}
```

**Comment by corymartin** [comment] 2022-12-18 18:06
Also, it seems that `FetcherError` is not exported to the `@xata.io/client` package?
https://github.com/xataio/client-ts/blob/6500a88b92fa4239f8e0fd104a3ad5aa6c9542a6/packages/client/src/api/errors.ts#L14

I was looking to do an `instanceof` test on the error. `XataError` is exported but `FetcherError` is not of that type.
Is this by design?

**Comment by SferaDev** [comment] 2022-12-18 18:08
> Also, it seems that `FetcherError` is not exported to the `@xata.io/client` package?
> https://github.com/xataio/client-ts/blob/6500a88b92fa4239f8e0fd104a3ad5aa6c9542a6/packages/client/src/api/errors.ts#L14
> 
> I was looking to do an `instanceof` test on the error. `XataError` is exported but `FetcherError` is not of that type.
> Is this by design?

That's a bug, will export it in next release

**Comment by SferaDev** [comment] 2022-12-19 14:43
@corymartin https://github.com/xataio/client-ts/releases/tag/%40xata.io/client%400.21.5

**Comment by kostasb** [comment] 2022-12-20 11:58
> Thanks @tsg
> 
> It worked with the TS client `await xata.db.Table.create()`
> 
> However with transactions - which I realize is still in beta - I get an error:
> 
> ```
> FetcherError: Bulk operation failed
> 
> {
>   status: 400,
>   errors: [
>     {
>       index: 0,
>       message: 'table [UserPrograms]: select record: invalid record: column [createdAt]: cannot be null'
>     }
>   ],
>   requestId: '6f657ab5-e132-9ac3-b5c5-acbce46232fd',
>   cause: undefined
> }
> ```

Hi @corymartin, thanks for the report. After checking our logs, it appears in this request a value of `null` was specified for the `createdAt` field in the transaction. For security purposes we do not log the content of your request, but the trace implies that a null value was specified.

In order for the column value to receive the default timestamp of`now`, the createdAt field shouldn't be present in the insert or update operation on the record. In case it is present but null. the error you encountered is returned.

Let us know if you are still encountering this issue and, if that's the case, how the transaction request body is created?

**Comment by corymartin** [comment] 2022-12-20 15:15
@kostasb 

The query I ran is:
```typescript
    const programId = uniqueId();
    await xata.transactions.run([
      {
        insert: {
          table: 'UserPrograms',
          record: { id: programId, user: uid, title: 'now test' },
        },
      },
      {
        insert: {
          table: 'UserOwnedPrograms',
          record: { user: uid, userProgram: programId },
        },
      },
    ]);
```

I just ran it a few more times, each getting the same error as above
`requestId: 'a9907441-d035-9a08-8a31-f49282469d53'`
`requestId: '5fbe42d3-337e-9a0f-ab8b-970e2d7e56d4'`
`requestId: '9d539135-3b2f-9992-b792-724bcce7ad8e'`

There are 2 date columns (`createdAt` and `updatedAt`) where the schema is
```json
        {
          "name": "createdAt",
          "type": "datetime",
          "notNull": true,
          "defaultValue": "now"
        }
```

**Comment by corymartin** [comment] 2022-12-20 15:23
Schema dump
```json
{
  "tables": [
    {
      "name": "Users",
      "columns": [
        {
          "name": "handle",
          "type": "string",
          "unique": true
        },
        {
          "name": "_handle",
          "type": "string",
          "unique": true
        },
        {
          "name": "profile",
          "type": "object",
          "columns": [
            {
              "name": "name",
              "type": "string"
            },
            {
              "name": "bio",
              "type": "text"
            },
            {
              "name": "location",
              "type": "string"
            },
            {
              "name": "website",
              "type": "string"
            }
          ]
        },
        {
          "name": "settings",
          "type": "object",
          "columns": [
            {
              "name": "appTheme",
              "type": "string"
            }
          ]
        },
        {
          "name": "createdAt",
          "type": "datetime",
          "notNull": true,
          "defaultValue": "now"
        },
        {
          "name": "updatedAt",
          "type": "datetime",
          "notNull": true,
          "defaultValue": "now"
        }
      ]
    },
    {
      "name": "UserPrograms",
      "columns": [
        {
          "name": "user",
          "type": "link",
          "link": {
            "table": "Users"
          }
        },
        {
          "name": "title",
          "type": "string",
          "notNull": true,
          "defaultValue": ""
        },
        {
          "name": "createdAt",
          "type": "datetime",
          "notNull": true,
          "defaultValue": "now"
        },
        {
          "name": "updatedAt",
          "type": "datetime",
          "notNull": true,
          "defaultValue": "now"
        }
      ]
    },
    {
      "name": "UserOwnedPrograms",
      "columns": [
        {
          "name": "user",
          "type": "link",
          "link": {
            "table": "Users"
          }
        },
        {
          "name": "userProgram",
          "type": "link",
          "link": {
            "table": "UserPrograms"
          }
        },
        {
          "name": "createdAt",
          "type": "datetime",
          "notNull": true,
          "defaultValue": "now"
        }
      ]
    }
  ]
}
```

**Comment by kostasb** [comment] 2022-12-21 10:05
Thank you for the additional details @corymartin , we will investigate and get back to you with our findings or a fix, if applicable.

**Comment by kostasb** [comment] 2022-12-23 10:34
@corymartin we confirmed the problem with transactions failing to use the default value is due to a bug and we are working on it. I will let you know as soon as the issue is resolved.

**Comment by kostasb** [comment] 2022-12-28 08:47
Hi @corymartin the issue with transactions + default values has been resolved. The transaction requests in your [earlier comment](https://github.com/xataio/client-ts/issues/819#issuecomment-1359546435) should work now!

Let us know in case you encounter any issues, here or at support@xata.io. Otherwise I believe we can close this current issue if all items are addressed?

**Comment by corymartin** [comment] 2022-12-28 14:14
@kostasb LGTM! It is working as expected now. Thanks for addressing this.

**Closed** 2022-12-28 15:00 UTC
Labels: bug
