### ISSUE TITLE
Discrepancy between summarize and aggregate

### ISSUE THREAD

**Issue by scrumptiousdev** [xataio/client-ts#873] opened 2023-01-26 06:15 UTC
**Describe the bug**

With same filter being applied, result of `sum` comes back differently between summarize and aggregate

**To Reproduce**

![Screenshot 2023-01-25 at 10 12 08 PM](https://user-images.githubusercontent.com/9010389/214769966-b49c5934-c58e-4520-b044-efb4ec50af76.png)

**Expected behavior**

Same result for both summarize and aggregate

**Software version**

"@xata.io/client": "^0.21.0"

**Comment by SferaDev** [comment] 2023-01-31 07:50
Hey @scrumptiousdev I raised this issue to our backend team, @kostasb will follow-up with them and let you know our findings. Also since it's not an SDK related problem, would you mind switching to support@xata.io channel?

**Comment by kostasb** [comment] 2023-01-31 09:22
Hi @scrumptiousdev if this issue persists please reach out to us by email to support@xata.io or by filling in the contact support form at https://support.xata.io/hc/en-us/requests/new, letting us know of your workspace id and database where this issue is observed. Optionally you can grant us an API key to query the data, if there is no sensitive information in it.

For the purpose of investigating further, I would suggest to start by making sure that the two endpoints, aggregate and summarize, "see" the same number of records in your database:

```

const aggCount = await xata.db.ledger.aggregate({
  numberOfRecords: {
    count: {},
  },
});

console.log(aggCount);

const sumCount = await xata.db.ledger.summarize({
    summaries: {
        "count_all_rows": { "count": "*" }
 }
});

console.log(sumCount);
```

since those two use different store types as mentioned in the `Store types` section in the [Limits](https://xata.io/docs/rest-api/limits) docs page.

Since the issue is not specific to the client but rather the aggregate and summarize APIs, let's close the issue and connect via Support.

**Closed by kostasb** 2023-01-31 09:22 UTC
Labels: bug, needs-triage
