### ISSUE TITLE
Error: invalid migration: outdated migration [branch ID: mig_cem92vdvjen51bb1aq3g, expected: mig_cem92v5vjen51bb1aq30]

### ISSUE THREAD

**Issue by JustMrMendez** [xataio/client-ts#843] opened 2022-12-28 19:40 UTC
**Describe the bug**
Only affects the branch that gives the error, not the full database, unable to apply migrations
Error: invalid migration: outdated migration [branch ID: mig_cem92vdvjen51bb1aq3g, expected: mig_cem92v5vjen51bb1aq30]

**To Reproduce**
Unable to reproduce, was creating and deleting a specific table multiple times, and trying to create
records in bulk multiple times.

**Expected behavior**

**Comment by JustMrMendez** [comment] 2022-12-28 19:54
@kostasb "This was likely byproduct of overlapping attempts to modify the schema."
is lock on the branch becomes permanent unless you delete the branch
![image](https://user-images.githubusercontent.com/56850299/209865441-1369e912-1aae-4e11-8aac-0d8cc5b0fc28.png)

**Comment by kostasb** [comment] 2022-12-28 20:23
@JustMrMendez The schema migration problems are triggered in the Xata "backend" side. We have created an internal issue to investigate further. Since the root cause of the issue is not in the client-ts we will close this issue here. I will let you know of our findings.

**Closed by kostasb** 2022-12-28 20:23 UTC
Labels: bug, needs-triage

**Comment by JustMrMendez** [comment] 2022-12-28 20:26
Oops, sorry i just had the tab open, i it occurred to me to open the issue, did not thought of that
